version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  hapi:
    build: ./hapi
    ports:
      - "9090:9090"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./hapi:/usr/app
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      HAPI_PORT: "${HAPI_PORT}"
      HAPI_HOST: "${HAPI_HOST}"
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1.cli-migrations
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${DATABASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "${HASURA_GRAPHQL_ENABLED_LOG_TYPES}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
