version: "3.6"
volumes:
  db_data:
services:
  postgres:
    container_name: "${STAGE}-${APP_NAME}-postgres"
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - ".env"
  hapi:
    container_name: "${STAGE}-${APP_NAME}-hapi"
    build: ./hapi
    ports:
      - "9090:9090"
    depends_on:
      - "postgres"
    volumes:
      - ./hapi:/usr/app
    env_file:
      - "./hapi/.env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/api/status"]
      interval: 10m
      timeout: 10s
      retries: 3
  hasura:
    container_name: "${STAGE}-${APP_NAME}-hasura"
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    build:
      context: ./hasura
      dockerfile: ./Dockerfile
      args:
        hasura_graphql_migrations_dir: /hasura-migrations
        hasura_graphql_metadata_dir: /hasura-metadata
    restart: on-failure
    env_file:
      - "./hasura/.env"
