version: "3.6"
volumes:
  db_data:
services:
  postgres:
    container_name: "${STAGE}-${APP_NAME}-postgres"
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - ".env"
  hapi:
    container_name: "${STAGE}-${APP_NAME}-hapi"
    build: ./hapi
    ports:
      - "9090:9090"
    depends_on:
      - "postgres"
    volumes:
      - ./hapi:/usr/app
    env_file:
      - "./hapi/.env"

  hasura:
    container_name: "${STAGE}-${APP_NAME}-hasura"
    build:
      context: ./hasura
      dockerfile: ./Dockerfile
      args:
        hasura_graphql_migrations_dir: /hasura-migrations
        hasura_graphql_metadata_dir: /hasura-metadata
    image: hasura
    ports:
      - "8085:8080"
    env_file:
      - "hasura/.env"
    restart: on-failure
    volumes:
      - .hasura/migrations:/hasura-migrations
      - .hasura/metadata:/hasura-metadata
    depends_on:
      - postgres
